title: dav's site
email: davidtranhq@gmail.com
description: CS + Math undergrad @ University of Western Ontario
show_downloads: false
google_analytics: UA-108144808-1
include: ['_pages']
color-scheme: manual
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
